fix: vitest.config.ts && debug info in ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -38,6 +38,7 @@ jobs:
         working-directory: backend
         run: |
           echo "Reading coverage from ./coverage/coverage-summary.json"
+          ls -R backend/coverage || echo "❌ coverage folder not found"
           COVERAGE=$(node -e "console.log(require('./coverage/coverage-summary.json').total.statements.pct)")
           echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
           echo "$COVERAGE" > ../last-coverage.txt
